import Link from "next/link";
import "../styles/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body>
        {children}

        <section className="flex h-screen">
          <nav className="menu-lateral">
            <div className="btn-expandir">
              <i className="bi bi-list"></i>
            </div>
            <ul className="">
              <li className="item-menu">
                <Link
                  href="/dashboard"
                  className="item-menu flex items-center hover:bg-gray-700 p-2 rounded"
                >
                  <span className="icon">
                    <i className="w-6 h-6 bi bi-house-door"></i>
                  </span>
                  <span className="txt-link">Início</span>
                </Link>
              </li>
              <li className="item-menu">
                <Link href="/dashboard/caixa">
                  <span className="icon">
                    <i className="bi bi-basket2-fill"></i>
                  </span>
                  <span className="txt-link">Caixa</span>
                </Link>
              </li>
              <li className="item-menu">
                <Link href="/dashboard/agenda">
                  <span className="icon">
                    <i className="bi bi-calendar-event"></i>
                  </span>
                  <span className="txt-link">Agenda</span>
                </Link>
              </li>
              <li className="item-menu">
                <Link href="/dashboard/relatorio">
                  <span className="icon">
                    <i className="bi bi-receipt"></i>
                  </span>
                  <span className="txt-link">Relatórios</span>
                </Link>
              </li>
              <li className="item-menu">
                <Link href="configuracoes">
                  <span className="icon">
                    <i className="bi bi-gear"></i>
                  </span>
                  <span className="txt-link">Configurações</span>
                </Link>
              </li>
              <li className="item-menu">
                <Link href="/dashboard/profile">
                  <span className="icon">
                    <i className="bi bi-person-fill"></i>
                  </span>
                  <span className="txt-link">Conta</span>
                </Link>
              </li>
            </ul>
          </nav>
        </section>
      </body>
    </html>
  );
}
